[manifest.dependencies]
serde = { version = "1.0.229", features = ["derive"] }
chrono = { version = "0.4.45", features = ["serde"] }

[types.custom.role]
derive-traits = ["PartialOrd", "Ord", "serde::Serialize"]

[types.custom.message_setting]
derive-traits = ["serde::Serialize"]

[types.custom.comment_setting]
derive-traits = ["serde::Serialize"]

[types.custom.visibility]
derive-traits = ["serde::Serialize"]

[types.custom.level_length]
derive-traits = ["serde::Serialize"]

[types.custom.difficulty]
derive-traits = ["serde::Serialize"]

[types.custom.demon_difficulty]
derive-traits = ["serde::Serialize"]

[types.custom.rating]
derive-traits = ["serde::Serialize"]
