CREATE TABLE friendships (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user1 INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    user2 INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    is_new1 BOOLEAN NOT NULL DEFAULT TRUE,
    is_new2 BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT unique_friendship UNIQUE (user1, user2),
    CONSTRAINT no_self_friend CHECK (user1 != user2)
);
