CREATE TABLE users (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    gjp2 VARCHAR(255) NOT NULL,
    save_data TEXT NOT NULL DEFAULT '',
    is_activated BOOLEAN NOT NULL DEFAULT TRUE,
    mod_level SMALLINT NOT NULL DEFAULT 0,
    udid TEXT NOT NULL DEFAULT '',

    stars INTEGER NOT NULL DEFAULT 0,
    demons INTEGER NOT NULL DEFAULT 0,
    creator_points INTEGER NOT NULL DEFAULT 0,
    diamonds INTEGER NOT NULL DEFAULT 0,
    moons INTEGER NOT NULL DEFAULT 0,
    secret_coins INTEGER NOT NULL DEFAULT 0,
    user_coins INTEGER NOT NULL DEFAULT 0,

    cube SMALLINT NOT NULL DEFAULT 1,
    ship SMALLINT NOT NULL DEFAULT 1,
    ball SMALLINT NOT NULL DEFAULT 1,
    ufo SMALLINT NOT NULL DEFAULT 1,
    wave SMALLINT NOT NULL DEFAULT 1,
    robot SMALLINT NOT NULL DEFAULT 1,
    spider SMALLINT NOT NULL DEFAULT 1,
    swing SMALLINT NOT NULL DEFAULT 1,
    jetpack SMALLINT NOT NULL DEFAULT 1,
    glow SMALLINT NOT NULL DEFAULT 0,
    explosion SMALLINT NOT NULL DEFAULT 1,
    icon SMALLINT NOT NULL DEFAULT 1,
    icon_type SMALLINT NOT NULL DEFAULT 0,

    color1 SMALLINT NOT NULL DEFAULT 0,
    color2 SMALLINT NOT NULL DEFAULT 3,
    color3 SMALLINT NOT NULL DEFAULT -1,

    message_setting SMALLINT NOT NULL DEFAULT 0,
    friend_setting SMALLINT NOT NULL DEFAULT 0,
    comment_setting SMALLINT NOT NULL DEFAULT 0,

    youtube VARCHAR(255) NOT NULL DEFAULT '',
    twitter VARCHAR(255) NOT NULL DEFAULT '',
    twitch VARCHAR(255) NOT NULL DEFAULT '',
    discord VARCHAR(255) NOT NULL DEFAULT '',
    instagram VARCHAR(255) NOT NULL DEFAULT '',
    tiktok VARCHAR(255) NOT NULL DEFAULT '',
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
)
